flowchart TD
%% generated in 0.01s
    packages__cli2gillm["packages.cli2gillm<br/>2 funcs"]
    packages__dsl2gillm["packages.dsl2gillm<br/>60 funcs"]
    packages__mcp2gillm["packages.mcp2gillm<br/>7 funcs"]
    packages__nlp2gillm["packages.nlp2gillm<br/>7 funcs"]
    packages__rest2gillm["packages.rest2gillm<br/>2 funcs"]
    packages__uri2gillm["packages.uri2gillm<br/>12 funcs"]
    src__gillm["src.gillm<br/>196 funcs"]
    src__gillm ==>|8| packages__dsl2gillm
    packages__mcp2gillm ==>|7| packages__dsl2gillm
    packages__rest2gillm ==>|6| packages__dsl2gillm
    packages__dsl2gillm ==>|4| src__gillm
    packages__cli2gillm -->|3| packages__dsl2gillm
    packages__uri2gillm -->|1| packages__dsl2gillm
    packages__nlp2gillm -->|1| packages__uri2gillm
    packages__nlp2gillm -->|1| packages__dsl2gillm
    packages__mcp2gillm -->|1| packages__nlp2gillm
    packages__dsl2gillm -->|1| packages__nlp2gillm
